apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  
spec:
  project: apps

  source:
    path: charts/jenkins
    repoURL: https://github.com/jenana-devops/argocd-demo.git
    targetRevision: HEAD

  destination:
    namespace: jenkins
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      